In [17]:
# O Conceito de Hoje: Criação de DataFrames Manuais (Dia 1)
# Para usar o Pandas no Google Colab, primeiro importamos a biblioteca dando a ela o apelido padrão de mercado: pd.

import pandas as pd


# Podemos transformar um dicionário onde cada chave é o nome de uma coluna e cada valor é uma lista de dados diretamente em uma tabela usando pd.DataFrame():

dados = {
    "jogador": ["Neymar Jr", "Barreal", "Gabriel Barbosa"],
    "posicao": ["Ponta Esquerda", "Meia Armador", "Centroavante"],
    "gols": [138, 36, 84]
}

tabela_santos = pd.DataFrame(dados)
display(tabela_santos)

           jogador         posicao  gols
0        Neymar Jr  Ponta Esquerda   138
1          Barreal    Meia Armador    36
2  Gabriel Barbosa    Centroavante    84

In [16]:
# EXERCICIO

import pandas as pd

dados_elenco = {
    "Jogador": ["Neymar", "Arthur", "Coutinho", "Brasao", "Luan Peres"],
    "Posicao": ["Atacante", "Meia Armador", "Meia Atacante", "Goleiro", "Zagueiro"],
    "Jogos": [100, 15, 6, 130, 101],
    "Assistencias": [10, 5, 5, 1, 3]
}

tabela_santos = pd.DataFrame(dados_elenco)
tabela_santos

      Jogador        Posicao  Jogos  Assistencias
0      Neymar       Atacante    100            10
1      Arthur   Meia Armador     15             5
2    Coutinho  Meia Atacante      6             5
3      Brasao        Goleiro    130             1
4  Luan Peres       Zagueiro    101             3