In [19]:
import pandas as pd

dados_jogadores = {
    "Atleta": ["João", "Maria", "Pedro", "Ana", "Lucas","Antonio"],
    "Posição": ["Atacante", "Meia", "Defensor", "Zagueiro", "Atacante","Meia"],
    "Jogos": [10, 25, 38, 13, 8, 15],
    "Desarmes": [8, 18, 20, 6, 4, 12]
}

df_combate = pd.DataFrame(dados_jogadores)

titulares_combate = df_combate[(df_combate["Jogos"] > 15) & (df_combate["Desarmes"] > 10)]
setor_central = df_combate[(df_combate["Posição"] == "Volante") | (df_combate["Posição"] == "Zagueiro")]

display(titulares_combate, setor_central)

  Atleta   Posição  Jogos  Desarmes
1  Maria      Meia     25        18
2  Pedro  Defensor     38        20

  Atleta   Posição  Jogos  Desarmes
3    Ana  Zagueiro     13         6